# Generated by Django 5.0.1 on 2024-02-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=1)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.comida')),
            ],
            options={
                'unique_together': {('token', 'comida')},
            },
        ),
    ]
